version: 2.1

jobs:
    build:
        executor: node/default

        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: pnpm
            - run:
                  name: Install dependencies
                  command: pnpm install

            - run:
                  name: Build
                  command: pnpm build

workflows:
    version: 2
    build:
        jobs:
            - build
