version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:20

        steps:
            - checkout

            - run:
                  name: Install dependencies
                  command: npm install

            - run:
                  name: Build
                  command: npm run build

workflows:
    version: 2
    build:
        jobs:
            - build
