name: CI

on:
    - push
    - pull_request
jobs:
    build:
        name: Install & Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
