name: npm audit

on:
    - push
    - pull_request
jobs:
    install:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
                  run_install: false
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
