name: Publish

on:
    release:

jobs:
    build:
        name: Publish webextension
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v5
              with:
                  node-version: 22
            - name: Build
              run: |
                  npm i -g pnpm
                  pnpm i
                  pnpm build
            - name: Upload & release
              uses: mnao305/chrome-extension-upload@v5.0.0
              with:
                  file-path: ctu-extension.zip
                  extension-id: lggkifjaacghbpebpcbaneimpogjbnmf
                  client-id: ${{ secrets.CLIENT_ID }}
                  client-secret: ${{ secrets.CLIENT_SECRET }}
                  refresh-token: ${{ secrets.REFRESH_TOKEN }}
